### ISSUE TITLE
Crash when returning if date picker was left open

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1201]
How to reproduce:
1. Create/Edit a card
2. Go to the Options tab
3. Click "Choose expiry date" under "Expiry date"
4. Switch to another app
5. Switch back to Catima

Device:
Fairphone 3, LineageOS for microG 19.1 (Android 12.1)

Crash:
```
FATAL EXCEPTION: main
Process: me.hackerchick.catima, PID: 29237
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.hackerchick.catima/protect.card_locker.LoyaltyCardEditActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment protect.card_locker.LoyaltyCardEditActivity$DatePickerFragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment protect.card_locker.LoyaltyCardEditActivity$DatePickerFragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at protect.card_locker.CatimaAppCompatActivity.onCreate(CatimaAppCompatActivity.java:24)
	at protect.card_locker.LoyaltyCardEditActivity.onCreate(LoyaltyCardEditActivity.java:308)
	at android.app.Activity.performCreate(Activity.java:8057)
	at android.app.Activity.performCreate(Activity.java:8037)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	... 12 more
Caused by: java.lang.NoSuchMethodException: protect.card_locker.LoyaltyCardEditActivity$DatePickerFragment.<init> []
	at java.lang.Class.getConstructor0(Class.java:2363)
	at java.lang.Class.getConstructor(Class.java:1759)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
	... 27 more
```

**Comment by lucile98-ode** [comment]
Hi, I'm gonna see what I can do for it :)

**Comment by TheLastProject** [comment]
Good luck and thanks for helping :)

**Comment by lucile98-ode** [comment]
Hi :) The pull-request is :
https://github.com/CatimaLoyalty/Android/pull/1212 !

**Comment by TheLastProject** [comment]
Your MR is actually not for this crash but for another feature (I still need to do the cleanup to deal with your MR, sorry for that).
