### ISSUE TITLE
Crash on opening card

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#1413]
Happening to me when trying to open a card after I loaded in debug cards before and now wiped app data and imported my actual data.

I can't help but notice that the long-press menu shows outdated data (cards that existed before the import):

![Screenshot_20230711-172146_Trebuchet](https://github.com/CatimaLoyalty/Android/assets/1885159/7ecae343-965b-45b0-b536-f2415a50349c)

Maybe a bug with trying to update the shortcut to a no longer existing card?

Not sure how to reproduce despite that my stable install is now broken.

```
FATAL EXCEPTION: main
Process: me.hackerchick.catima, PID: 8002
java.lang.NullPointerException: Attempt to read from field 'int protect.card_locker.LoyaltyCard.id' on a null object reference in method 'androidx.core.content.pm.ShortcutInfoCompat$Builder protect.card_locker.ShortcutHelper.createShortcutBuilder(android.content.Context, protect.card_locker.LoyaltyCard)'
	at protect.card_locker.ShortcutHelper.createShortcutBuilder(ShortcutHelper.java:139)
	at protect.card_locker.ShortcutHelper.updateShortcuts(ShortcutHelper.java:93)
	at protect.card_locker.MainActivity.onRowClicked(MainActivity.java:873)
	at protect.card_locker.LoyaltyCardCursorAdapter.lambda$applyClickEvents$2(LoyaltyCardCursorAdapter.java:229)
	at protect.card_locker.LoyaltyCardCursorAdapter.$r8$lambda$tjRlnyeWB9jTEpjboZyzPPFIhgs(LoyaltyCardCursorAdapter.java:0)
	at protect.card_locker.LoyaltyCardCursorAdapter$$ExternalSyntheticLambda2.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by TheLastProject** [comment]
Okay, this crash is not newly introduced in 2.25.0, according to Google Play stats someone else had this crash on 2.24.2, 9 days ago (samsung dm1q (Galaxy S23) running Android 13 (SDK 33)).

So, good news, the rollout to production doesn't have to be cancelled.

Bad news: Google only keeps the last 60 days of crash logs and has no way to export them to GitHub or email or anything, so I have no clue what release this crash started happening.

**Comment by TheLastProject** [comment]
On the broken install, the Android "Device Control" menu also gets stuck loading:

![image](https://github.com/CatimaLoyalty/Android/assets/1885159/25eed385-59bd-4a1a-b92e-d0c6625a8e35)

This really seems to be shortcut-related.
