### ISSUE TITLE
Crashing string introduced in nb_NO

### ISSUE THREAD

**Issue by comradekingu** [CatimaLoyalty/Android#800]
For some reason I forgot the ending tags in https://hosted.weblate.org/translate/catima/catima/nb_NO/?checksum=f59d444c872649e8#history
which then tagged on "%d" instead of "%s" automatically,
possibly beause of https://hosted.weblate.org/changes/?page=2&limit=20&lang=nb_NO&component=catima&project=catima
>Parsing of the "app/src/main/res/values-nb-rNO/strings.xml" file was enforced. 

This means the app crashes in nb_NO, but not in other locales.
Just thought I'd chime in if the process can be improved.
Should be added to the next changelog too, as it is now (hopefully) fixed.

<details>
FATAL EXCEPTION: main
Process: me.hackerchick.catima, PID: 20986
java.util.IllegalFormatConversionException: d != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4403)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2885)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2839)
	at java.util.Formatter.format(Formatter.java:2524)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2911)
	at android.content.res.Resources.getQuantityString(Resources.java:518)
	at protect.card_locker.Utils.formatBalance(Utils.java:213)
	at protect.card_locker.LoyaltyCardCursorAdapter$LoyaltyCardListItemViewHolder.setBalanceField(LoyaltyCardCursorAdapter.java:276)
	at protect.card_locker.LoyaltyCardCursorAdapter.onBindViewHolder(LoyaltyCardCursorAdapter.java:93)
	at protect.card_locker.LoyaltyCardCursorAdapter.onBindViewHolder(LoyaltyCardCursorAdapter.java:34)
	at protect.card_locker.BaseCursorAdapter.onBindViewHolder(BaseCursorAdapter.java:34)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
	at android.view.View.layout(View.java:22466)
	at android.view.ViewGroup.layout(ViewGroup.java:6304)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[/details]

**Comment by TheLastProject** [comment]
Oh, that's actually my fault as PR #790 failed and I manually fixed it but used the wrong symbol: https://github.com/CatimaLoyalty/Android/pull/790/commits/ac6bffcc6739ce92571e5a3309e2fc889dd7ae4d

I am kinda disappointed both lint and spotBugs didn't complain about this...

Thank you for your report so quickly after the F-Droid release, so I could still halt the Google Play rollout of 2.15.0 before it got through Google's review. I've told Weblate to create a new PR early and will do a new release with the fixed string after work.
