### ISSUE TITLE
java.lang.RuntimeException: Unable to resume activity {me.hackerchick.catima/protect.card_locker.LoyaltyCardEditActivity}: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: de

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#808]
```
FATAL EXCEPTION: Thread-2
Process: me.hackerchick.catima, PID: 26060
java.lang.RuntimeException: Unable to resume activity {me.hackerchick.catima/protect.card_locker.LoyaltyCardEditActivity}: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: de
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3657)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3697)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2927)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:5)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Unknown Source:0)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6662)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: de
	at java.util.Currency.getInstance(Currency.java:139)
	at protect.card_locker.LoyaltyCardEditActivity$5.afterTextChanged(LoyaltyCardEditActivity.java:451)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:9409)
	at android.widget.TextView.setText(TextView.java:5432)
	at android.widget.TextView.setText(TextView.java:5279)
	at android.widget.EditText.setText(EditText.java:113)
	at android.widget.TextView.setText(TextView.java:5236)
	at protect.card_locker.LoyaltyCardEditActivity.formatBalanceCurrencyField(LoyaltyCardEditActivity.java:953)
	at protect.card_locker.LoyaltyCardEditActivity.onResume(LoyaltyCardEditActivity.java:815)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnResume(MonitoringInstrumentation.java:1)
	at android.app.Activity.performResume(Activity.java:7182)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3632)
	... 28 more
```

https://user-images.githubusercontent.com/1885159/153559156-ec7940d4-3749-463f-8495-ccc6994efb0f.mp4

**Comment by TheLastProject** [comment]
Fixed in a5901700b4c9ade4464b7e1693e6df10da3ddd64.
