### ISSUE TITLE
The app throws ActivityNotFoundException when clicking "USE EXTERNAL APP" button

### ISSUE THREAD

**Issue by androidAppGuard** [CatimaLoyalty/Android#880]
**the environment is as follows:**
```
App version: v1.6.0
Android version: 6.0
Device: Nexux_5X
```
**The steps to reproduce:**
![14_CatimaLoyalty_ActivityNotFoundException.gif](https://s2.loli.net/2022/05/13/W6mubyYj5nc3EvT.gif)
**The exception log is as follows:**
```
05-13 06:09:58.632 10351-10351/me.hackerchick.catima.debug E/Catima: No activity found to handle intent
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
        at android.app.Activity.startActivityForResult(Activity.java:3917)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:3877)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at protect.card_locker.ImportExportActivity.chooseFileWithIntent(ImportExportActivity.java:283)
        at protect.card_locker.ImportExportActivity.access$000(ImportExportActivity.java:32)
        at protect.card_locker.ImportExportActivity$3.onClick(ImportExportActivity.java:109)
        at android.view.View.performClick(View.java:5198)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Altonss** [comment]
Are you using Catima v.1.6.0 as indicated? Because this is a very old version: this current release is 2.13.6
So I would advise you to update the app, this might resolve your issue!

**Comment by androidAppGuard** [comment]
yes, our testing tool found this bug, so we would like to verify if this bug is accurate with developers, to check the effectiveness of the testing  tool, thanks!

**Comment by Altonss** [comment]
But please test with the current version and don't open the issues until you have verified you are not on the latest release :) This causes unnecessary work for the maintainers trying to triage the bug reports!

**Comment by androidAppGuard** [comment]
Thanks, I will test the current version and close this issue

**Comment by androidAppGuard** [comment]
I test in the current version and the issue has been fixed
