### ISSUE TITLE
the app will throw IllegalArgumentException if we enter content (number or character) in Card ID TextEditor

### ISSUE THREAD

**Issue by androidAppGuard** [CatimaLoyalty/Android#881]
**the environment is as follows:**
```
App version: v1.6.0
Android version: 6.0
Device: Nexux_5X
```
**The steps to reproduce:**
![14_CatimaLoyalty_IllegalArgumentException.gif](https://s2.loli.net/2022/05/13/O9RalXxAWPUSLgs.gif)
**The exception log is as follows:**
```
05-13 06:22:52.495 10661-10694/me.hackerchick.catima.debug E/Catima: Failed to generate barcode of type UPC_A: 1
    com.google.zxing.WriterException: java.lang.IllegalArgumentException: Requested contents should be 11 or 12 digits long, but got 1
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:119)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalArgumentException: Requested contents should be 11 or 12 digits long, but got 1
        at com.google.zxing.oned.UPCAWriter.preencode(UPCAWriter.java:69)
        at com.google.zxing.oned.UPCAWriter.encode(UPCAWriter.java:51)
        at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:102)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:112)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:22) 
        at android.os.AsyncTask$2.call(AsyncTask.java:295) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 

05-13 06:22:53.832 10661-10690/me.hackerchick.catima.debug E/Catima: Failed to generate barcode of type CODE_39: 1w
    com.google.zxing.WriterException: java.lang.IllegalArgumentException: Bad contents: 1w
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:119)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalArgumentException: Bad contents: 1w
        at com.google.zxing.oned.Code39Writer.encode(Code39Writer.java:58)
        at com.google.zxing.oned.OneDimensionalCodeWriter.encode(OneDimensionalCodeWriter.java:67)
        at com.google.zxing.oned.Code39Writer.encode(Code39Writer.java:42)
        at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:102)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:112)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:22) 
        at android.os.AsyncTask$2.call(AsyncTask.java:295) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 

05-13 06:22:55.601 10661-10694/me.hackerchick.catima.debug E/Catima: Failed to generate barcode of type CODE_39: 1wa
    com.google.zxing.WriterException: java.lang.IllegalArgumentException: Bad contents: 1wa
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:119)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalArgumentException: Bad contents: 1wa
        at com.google.zxing.oned.Code39Writer.encode(Code39Writer.java:58)
        at com.google.zxing.oned.OneDimensionalCodeWriter.encode(OneDimensionalCodeWriter.java:67)
        at com.google.zxing.oned.Code39Writer.encode(Code39Writer.java:42)
        at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:102)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:112)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:22) 
        at android.os.AsyncTask$2.call(AsyncTask.java:295) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
05-13 06:22:55.615 10661-10694/me.hackerchick.catima.debug E/Catima: Failed to generate barcode of type CODABAR: 1wa
    com.google.zxing.WriterException: java.lang.IllegalArgumentException: Invalid start/end guards: 1wa
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:119)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalArgumentException: Invalid start/end guards: 1wa
        at com.google.zxing.oned.CodaBarWriter.encode(CodaBarWriter.java:58)
        at com.google.zxing.oned.OneDimensionalCodeWriter.encode(OneDimensionalCodeWriter.java:67)
        at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:102)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:112)
        at protect.card_locker.BarcodeImageWriterTask.doInBackground(BarcodeImageWriterTask.java:22) 
        at android.os.AsyncTask$2.call(AsyncTask.java:295) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by Altonss** [comment]
Are you using Catima v.1.6.0 as indicated? Because this is a very old version: this current release is 2.13.6
So I would advise you to update the app, this might resolve your issue!
(same as #880 )

**Comment by androidAppGuard** [comment]
Thank you very much for answering this issue, we want to verify if this bug is accurate for checking the effectiveness of the testing tool, thanks!

**Comment by androidAppGuard** [comment]
Thanks, I will test the current version  and close this issue.
